### ISSUE TITLE
quiz blank/question missing?

### ISSUE THREAD

**Issue by meganewing** [sr320/course-fish541-2024#1]
Canvas quiz doesn't show any questions -- tried yesterday on my phone (both through app and safari) and didn't show anything. Finally have laptop access again this morning and still not showing.

<img width="919" alt="Screen Shot 2024-04-13 at 7 42 00 AM" src="https://github.com/sr320/course-fish541-2024/assets/66333757/e869dc5c-34f9-4846-9eaa-811aa40c7f43">
<img width="682" alt="Screen Shot 2024-04-13 at 7 42 11 AM" src="https://github.com/sr320/course-fish541-2024/assets/66333757/333869b1-8997-4464-a4a0-7200e1a96881">

In any case, [here's](https://github.com/meganewing/clamgonads-macsamples/blob/main/output/fastQC-output/multiqc_report.html) my mutliqc report

**Comment by shedurkin** [comment]
Here's my stuff:
QC code: https://github.com/RobertsLab/project-cod-temperature/blob/main/code/05-cod-RNAseq-trimming.md
MultiQC report (trimmed reads): https://github.com/RobertsLab/project-cod-temperature/blob/main/output/05-cod-RNAseq-trimming/trimmed-fastqc/multiqc_report.html
Link to raw data: https://owl.fish.washington.edu/nightingales/G_macrocephalus/30-943133806/
